# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registered_people',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
