# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registered_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_people',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
