# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180617_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registered_people',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
